[tools]
argon = "argon-rbx/argon@2.0.13"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.26.1"
stylua = "JohnnyMorganz/StyLua@0.20.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"