[package]
name = "lumin/ui-framework"
description = "A lightweight and embeddable UI framework"
version = "0.3.0"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
debugger = "lumin/debugger@^0.4.0"
