[package]
name = "lumin/aegis"
description = "A simple strictly typed UI framework made specifically for Roblox"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = [
	"default.project.json",
	"src",
	"src/**",
	"LICENSE",
	"wally.toml",
	"README.md",
]