name: Build standalone version

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
    build:
        name: New Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Aftman
              uses: ok-nick/setup-aftman@v0.4.2

            - name: Install Wally dependencies
              run: wally install

            - name: Format code
              run: stylua src/

            - name: Build standalone
              run: argon build standalone.project.json --output ./Standalone.rbxm

            - name: Create release
              id: create_release
              uses: softprops/action-gh-release@v2.0.6
              with:
                tag_name: ${{ github.ref_name }}
                name: ${{ github.ref_name }}
                draft: true
                generate_release_notes: true
                files: |
                  ./Standalone.rbxm
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}