name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    bump:
        name: Bump Versions
        runs-on: ubuntu-latest
        outputs:
          release-body: ${{ steps.update-changelog.outputs.release-notes }}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              ref: 'main'

          - name: Update changelog
            id: update-changelog
            uses: thomaseizinger/keep-a-changelog-new-release@3.1.0
            with:
              tag: ${{ github.ref_name }}
              changelogPath: 'docs/changelog.md'

          - name: Commit and push
            uses: EndBug/add-and-commit@v9
            with:
              message: Bump version to ${{ github.ref_name }}
              default_author: github_actions

    build:
        name: Build
        runs-on: ubuntu-latest
        needs: bump
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup Pesde
            uses: 2jammers/setup-pesde@v0.3.0
            with:
              cache: 'true'
              pesde-version: 'v0.5.1+registry.0.1.0'

          - name: Install dependencies
            run: pesde install

          - name: Generate sourcemap
            run: rojo sourcemap standalone.project.json --output sourcemap.json

          - name: Format code
            run: stylua src/

          - name: Build standalone
            run: rojo build standalone.project.json --output ./Standalone.rbxm

          - name: Draft release
            uses: softprops/action-gh-release@v2.2.0
            with:
              tag_name: ${{ github.ref_name }}
              name: ${{ github.ref_name }}
              prerelease: ${{ contains(github.ref_name, 'rc') }}
              generate_release_notes: true
              body: |
                ## Changelog
                ${{ needs.bump.outputs.release-body }}
              files: |
                ./Standalone.rbxm

    package:
        name: Package
        runs-on: ubuntu-latest
        needs: bump
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Pesde
          uses: 2jammers/setup-pesde@v0.3.0
          with:
            pesde-version: 'v0.5.1+registry.0.1.0'
            token: '${{ secrets.PESDE_TOKEN }}'

        - name: Publish
          run: |
            pesde install
            pesde publish -y
